# Generated by Django 4.1.7 on 2023-03-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewProductAddModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('images', models.FileField(upload_to='img/')),
                ('price', models.CharField(max_length=100)),
                ('discount', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tbl_product_add',
            },
        ),
        migrations.CreateModel(
            name='UserRegistraionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'tbl_ragistration',
            },
        ),
    ]
